"""Full RU/EN task markdown for lang task notebooks (recommendation #3)."""

from __future__ import annotations

# Each entry: (ru_lines, en_lines, optional_code_starter_lines or None)


def _pairs(*items: tuple[list[str], list[str], list[str] | None]) -> list[tuple[list[str], list[str], list[str] | None]]:
    return list(items)


NUMPY = _pairs(
    (
        [
            "## Задание 1.1",
            "Создайте массив из списка [10, 20, 30, 40, 50, 60].",
            "Выведите его shape, ndim, size, dtype.",
            "Создайте матрицу 3×4, заполненную единицами, и матрицу 2×5, заполненную числом 7.5.",
            "Сгенерируйте массив из 8 чисел от 0 до 14 с шагом 2.",
        ],
        [
            "## Task 1.1",
            "Create an array from [10, 20, 30, 40, 50, 60].",
            "Print its shape, ndim, size, and dtype.",
            "Create a 3×4 matrix of ones and a 2×5 matrix filled with 7.5.",
            "Generate 8 numbers from 0 to 14 with step 2.",
        ],
        None,
    ),
    (
        [
            "## Задание 1.2",
            "Создайте массив чисел от 0 до 23 (np.arange).",
            "Преобразуйте его в матрицу 4×6.",
            "Преобразуйте ту же последовательность в 3D-тензор формы (2, 3, 4), используя -1 для одной из осей.",
            "Возьмите матрицу 4×6, сделайте её одномерной через ravel(), измените первый элемент на 999 и проверьте, изменился ли исходник.",
            "Повторите шаг 4 через flatten(). Что произошло?",
        ],
        [
            "## Task 1.2",
            "Create an array 0…23 with np.arange.",
            "Reshape to 4×6.",
            "Reshape the same data to a 3D tensor (2, 3, 4) using -1 for one axis.",
            "Ravel the 4×6 matrix, set the first element to 999 — did the original change?",
            "Repeat with flatten(). What happened?",
        ],
        None,
    ),
    (
        [
            "## Задание 1.3",
            "Сгенерируйте массив из 10 000 случайных чисел от 50 до 1500 (np.random.uniform).",
            "Проверьте dtype и размер в байтах (arr.nbytes).",
            "Приведите массив к float32, снова проверьте nbytes. Насколько сократилась память?",
            "Округлите все значения до 2 знаков (векторно, без цикла).",
            "Преобразуйте массив в форму (250, 40) — таблица «250 дней × 40 категорий».",
        ],
        [
            "## Task 1.3",
            "Generate 10,000 random floats from 50 to 1500 (np.random.uniform).",
            "Check dtype and nbytes.",
            "Cast to float32; check nbytes again. How much memory did you save?",
            "Round to 2 decimals (vectorized, no loop).",
            "Reshape to (250, 40) — a “250 days × 40 categories” table.",
        ],
        None,
    ),
    (
        [
            "## Задание 2.1",
            "Создайте 1D-массив из 30 элементов (числа 1…30).",
            "Срез: элементы с 10-го по 20-й включительно.",
            "Булева маска для чётных чисел.",
            "Замените все значения < 15 на -1 в исходном массиве. Выведите первые 10 элементов.",
        ],
        [
            "## Task 2.1",
            "Create a 1D array of 30 elements (numbers 1…30).",
            "Slice elements 10 through 20 inclusive.",
            "Build a boolean mask for even numbers.",
            "Replace values < 15 with -1 in place; print the first 10 elements.",
        ],
        None,
    ),
    (
        [
            "## Задание 2.2",
            "Матрица 5×5 случайных целых от 10 до 90.",
            "Числа < 30 → 0, > 70 → 100 (np.where или np.select).",
            "Индексы элементов, равных 100 (np.argwhere / np.where).",
            "Обнулите последний столбец срезом.",
        ],
        [
            "## Task 2.2",
            "5×5 matrix of random integers from 10 to 90.",
            "Values < 30 → 0, > 70 → 100 (np.where / np.select).",
            "Indices where the value equals 100.",
            "Zero the last column with slicing.",
        ],
        None,
    ),
    (
        [
            "## Задание 2.3",
            "Матрица 1000×3: суммы ~N(500,200), кол-во товаров [1,10], возврат [0,1].",
            "Фильтр: сумма > 800 и возврат == 0. Доля таких строк.",
            "Столбец segment: Premium / Standard / Low (по условиям из задания).",
            "Добавьте segment как 4-й столбец (dtype=object).",
        ],
        [
            "## Task 2.3",
            "1000×3 matrix: amounts ~N(500,200), item count [1,10], return flag [0,1].",
            "Filter amount > 800 and return == 0; compute their share.",
            "Add segment column Premium / Standard / Low.",
            "Append segment as a 4th column (object dtype).",
        ],
        None,
    ),
    (
        [
            "## Задание 3.1",
            "Матрица 4×5 случайных чисел.",
            "Прибавьте к каждой строке [1,2,3,4,5].",
            "Прибавьте [10,20,30,40] по столбцам (исправьте ValueError через newaxis/reshape).",
            "Умножьте каждый элемент на максимум матрицы.",
        ],
        [
            "## Task 3.1",
            "4×5 random matrix.",
            "Add [1,2,3,4,5] to each row.",
            "Add [10,20,30,40] per column (fix shape with newaxis).",
            "Multiply every element by the matrix maximum.",
        ],
        None,
    ),
    (
        [
            "## Задание 3.2",
            "1 000 000 чисел N(0,1).",
            "Функция с for: x>0 → x², иначе abs(x). Замер времени.",
            "Векторный вариант через np.where. Замер времени.",
            "Выведите time_loop / time_vec.",
        ],
        [
            "## Task 3.2",
            "1,000,000 draws from N(0,1).",
            "for-loop: square if positive else abs; time it.",
            "Vectorized np.where version; time it.",
            "Print time_loop / time_vec.",
        ],
        None,
    ),
    (
        [
            "## Задание 3.3",
            "Матрица (1000, 5) случайных положительных чисел.",
            "Min и max по каждому столбцу (axis=0).",
            "Min–max нормализация: (x - min) / (max - min) одной строкой.",
            "Проверьте: min столбца ≈ 0, max ≈ 1.",
        ],
        [
            "## Task 3.3",
            "(1000, 5) positive random matrix.",
            "Min/max per column (axis=0).",
            "Min–max scale to [0, 1] in one expression.",
            "Verify column mins ≈ 0 and maxes ≈ 1.",
        ],
        None,
    ),
    (
        [
            "## Босс-файт: векторная подготовка датасета",
            "1. Клиппинг: значения > 95-го перцентиля → p95 (NaN не трогать).",
            "2. Импутация: NaN → медиана столбца.",
            "3. Сегменты VIP / Active / AtRisk / Standard (np.select, приоритет сверху вниз).",
            "4. Min–max нормализация 4 числовых столбцов.",
            "**Ограничения:** только NumPy, без циклов for/while, < 0.3 сек.",
        ],
        [
            "## Boss fight: vector data prep",
            "1. Clip values above the 95th percentile per column (leave NaN untouched).",
            "2. Fill NaN with column median.",
            "3. Segments VIP / Active / AtRisk / Standard via np.select (priority top to bottom).",
            "4. Min–max normalize four numeric columns.",
            "**Rules:** NumPy only, no for/while loops, runtime < 0.3s.",
        ],
        None,
    ),
)


FUNDAMENTALS = _pairs(
    (
        [
            "## Задание 5.1",
            "**Цель:** типы, фильтрация, выбор колонок.",
            "Создайте DataFrame из словаря: `user_id`, `status`, `revenue` (как в условии).",
            "Проверьте типы через `df.info()`. Приведите `user_id` к str, `status` к category.",
            "Отфильтруйте строки, где `status == 'active'` и `revenue > 200`.",
            "Выберите только колонки `user_id` и `revenue`.",
        ],
        [
            "## Task 5.1",
            "**Goal:** dtypes, filtering, column selection.",
            "Create a DataFrame from a dict with `user_id`, `status`, `revenue` (as in the brief).",
            "Inspect dtypes with `df.info()`. Cast `user_id` to str and `status` to category.",
            "Filter rows where `status == 'active'` and `revenue > 200`.",
            "Keep only `user_id` and `revenue`.",
        ],
        None,
    ),
    (
        [
            "## Задание 5.2",
            "**Цель:** `.loc`, `.iloc`, копии без предупреждений.",
            "Создайте DataFrame 5×3 с индексом A–E и колонками x, y, z (значения 1–15).",
            "Через `.loc` замените значение в строке C, колонке y на 999.",
            "Через `.iloc` обнулите последнюю строку.",
            "Подтаблица только x и z для строк B и D; в копии установите z = -1 без изменения исходника.",
        ],
        [
            "## Task 5.2",
            "**Goal:** `.loc`, `.iloc`, safe copies.",
            "Create a 5×3 DataFrame with index A–E and columns x, y, z (values 1–15).",
            "With `.loc`, set row C, column y to 999.",
            "With `.iloc`, zero the last row.",
            "Subset columns x and z for rows B and D; in a copy set z = -1 without mutating the original.",
        ],
        None,
    ),
    (
        [
            "## Задание 5.3",
            "**Цель:** даты, очистка, экспорт.",
            "Сгенерируйте DataFrame: `order_id` (ORD-0001…), `date_str` (DD.MM.YYYY), `amount` (с NaN и отрицательными), `region`.",
            "Преобразуйте `date_str` в datetime; оставьте только 2024 год.",
            "Замените NaN в amount на 0; удалите строки с amount < 0.",
            "Добавьте `tier`: High если amount > 5000, иначе Low (`np.where`).",
            "Сохраните `clean_orders.csv` без индекса.",
        ],
        [
            "## Task 5.3",
            "**Goal:** dates, cleaning, export.",
            "Build a DataFrame: `order_id` (ORD-0001…), `date_str` (DD.MM.YYYY), `amount` (with NaN/negatives), `region`.",
            "Parse dates; keep 2024 only.",
            "fillna(0) on amount; drop rows with amount < 0.",
            "Add `tier`: High if amount > 5000 else Low (`np.where`).",
            "Save `clean_orders.csv` with index=False.",
        ],
        None,
    ),
    (
        [
            "## Задание 6.1",
            "**Цель:** `groupby` + именованные агрегации.",
            "DataFrame: category (A/B/C), product (X/Y), sales (10–100).",
            "Сумма продаж по category.",
            "Сумма и среднее по category + product; колонки `total_sales`, `avg_sales`.",
        ],
        [
            "## Task 6.1",
            "**Goal:** `groupby` + named aggregations.",
            "DataFrame: category (A/B/C), product (X/Y), sales (10–100).",
            "Sum sales per category.",
            "Sum and mean per category + product; columns `total_sales`, `avg_sales`.",
        ],
        None,
    ),
    (
        [
            "## Задание 6.2",
            "**Цель:** несколько метрик на группу, фильтр групп.",
            "DataFrame: user_id, region, order_amount, is_completed (bool).",
            "По region: total_revenue, avg_order, completed_orders (sum bool), total_orders.",
            "Оставьте регионы с total_orders >= 50; `reset_index()`.",
            "**Разрешено:** groupby, agg, reset_index. **Запрещено:** apply, циклы.",
        ],
        [
            "## Task 6.2",
            "**Goal:** multi-metric group stats and group filter.",
            "DataFrame: user_id, region, order_amount, is_completed (bool).",
            "Per region: total_revenue, avg_order, completed_orders (sum bool), total_orders.",
            "Keep regions with total_orders >= 50; `reset_index()`.",
            "**Allowed:** groupby, agg, reset_index. **Forbidden:** apply, loops.",
        ],
        None,
    ),
    (
        [
            "## Задание 6.3",
            "**Цель:** `transform` без изменения формы таблицы.",
            "DataFrame: user_id, category, monthly_spend.",
            "`category_avg_spend` — среднее по category через transform.",
            "`spend_share` = monthly_spend / category_avg_spend.",
            "`is_high_value` если monthly_spend > 1.5 × category_avg_spend.",
        ],
        [
            "## Task 6.3",
            "**Goal:** `transform` without changing row count.",
            "DataFrame: user_id, category, monthly_spend.",
            "`category_avg_spend` via transform on category.",
            "`spend_share` = monthly_spend / category_avg_spend.",
            "`is_high_value` when monthly_spend > 1.5 × category_avg_spend.",
        ],
        None,
    ),
    (
        [
            "## Задание 7.1",
            "**Цель:** merge с validate, fillna после склейки.",
            "df_users: user_id 1…100, tier; df_orders: order_id, user_id (1…90), amount.",
            "left merge с `validate='1:m'`; amount NaN → 0.",
            "Общая выручка по tier.",
        ],
        [
            "## Task 7.1",
            "**Goal:** merge with validate, post-merge fillna.",
            "df_users: user_id 1…100, tier; df_orders: order_id, user_id (1…90), amount.",
            "left merge with `validate='1:m'`; fill amount NaN with 0.",
            "Total revenue by tier.",
        ],
        None,
    ),
    (
        [
            "## Задание 7.2",
            "**Цель:** concat + pivot_table.",
            "Три DataFrame q1, q2, q3 (product, region, sales); добавьте quarter Q1–Q3.",
            "Вертикальный concat; pivot: index region, columns quarter, values sales.",
            "Колонка growth_q3_vs_q2 = Q3 − Q2.",
        ],
        [
            "## Task 7.2",
            "**Goal:** concat + pivot_table.",
            "Three DataFrames q1, q2, q3 (product, region, sales); add quarter Q1–Q3.",
            "Concat vertically; pivot: index region, columns quarter, values sales.",
            "Column growth_q3_vs_q2 = Q3 − Q2.",
        ],
        None,
    ),
    (
        [
            "## Задание 7.3",
            "**Цель:** melt и доли через transform.",
            "df_wide: city, jan_rev, feb_rev, mar_rev.",
            "melt → month, revenue; доля месяца от выручки города (groupby + transform).",
            "Фильтр share > 0.35.",
        ],
        [
            "## Task 7.3",
            "**Goal:** melt and shares via transform.",
            "df_wide: city, jan_rev, feb_rev, mar_rev.",
            "melt → month, revenue; month share of city revenue (groupby + transform).",
            "Filter share > 0.35.",
        ],
        None,
    ),
)


PIPELINES = _pairs(
    (
        [
            "🔴 **Сквозной пайплайн: users + orders → metrics_by_region**",
            "**Контекст:** `users.csv` (user_id, signup_date, region) и `orders.csv` (order_id, user_id, order_date, amount).",
            "1. Загрузите оба файла с явным dtype; `user_id` → str в обоих.",
            "2. left merge (`validate='1:m'`); заказы только **2023**; amount NaN → 0.",
            "3. По region: total_revenue, avg_order, active_users (уникальные user_id с amount > 0).",
            "4. revenue_share — доля выручки региона от общей.",
            "5. Сохраните `metrics_by_region.csv` без индекса.",
            "**Критерий:** <30 строк кода, 0 циклов, файл открывается в Excel.",
        ],
        [
            "🔴 **End-to-end pipeline: users + orders → metrics_by_region**",
            "**Context:** `users.csv` (user_id, signup_date, region) and `orders.csv` (order_id, user_id, order_date, amount).",
            "1. Load both with explicit dtypes; cast `user_id` to str in both.",
            "2. left merge (`validate='1:m'`); keep **2023** orders only; fill amount NaN with 0.",
            "3. Per region: total_revenue, avg_order, active_users (unique user_id with amount > 0).",
            "4. revenue_share — region revenue / grand total.",
            "5. Save `metrics_by_region.csv` with index=False.",
            "**Success:** <30 lines, no loops, Excel-friendly CSV.",
        ],
        ["# users.csv sample:", "# U0001,01.01.2022,EU"],
    ),
    (
        [
            "🔴 **Высокодоходные кварталы (sales_wide.csv)**",
            "1. melt: id_vars product, region; quarter, revenue.",
            "2. total_year через transform('sum') по product+region.",
            "3. Фильтр revenue > 0.35 × total_year.",
            "4. pivot_table → product × quarter; fillna(0).",
            "5. `high_impact_quarters.csv` без индекса.",
        ],
        [
            "🔴 **High-impact quarters (sales_wide.csv)**",
            "1. melt: id_vars product, region; columns quarter, revenue.",
            "2. total_year via transform('sum') per product+region.",
            "3. Filter revenue > 0.35 × total_year.",
            "4. pivot_table → product × quarter; fillna(0).",
            "5. Save `high_impact_quarters.csv` with index=False.",
        ],
        ["# sales_wide sample:", "# Widget_A,North,9980,8451,9906,1775"],
    ),
    (
        [
            "📊 **Когортное удержание (transactions.csv)**",
            "1. Загрузка; user_id str; parse_dates.",
            "2. Удалить amount <= 0.",
            "3. cohort — месяц первой покупки (YYYY-MM); tx_month — месяц транзакции.",
            "4. groupby cohort, tx_month → active_users (nunique).",
            "5. cohort_size и retention_rate = active_users / cohort_size.",
            "6. Фильтр cohort_size >= 20; month_diff ∈ [0, 5].",
            "7. `cohort_retention_real.csv`.",
            "**Запрещено:** merge, concat.",
        ],
        [
            "📊 **Cohort retention (transactions.csv)**",
            "1. Load; user_id str; parse_dates.",
            "2. Drop amount <= 0.",
            "3. cohort = first purchase month (YYYY-MM); tx_month per transaction.",
            "4. groupby cohort, tx_month → active_users (nunique).",
            "5. cohort_size and retention_rate = active_users / cohort_size.",
            "6. Filter cohort_size >= 20; month_diff in [0, 5].",
            "7. Save `cohort_retention_real.csv`.",
            "**Forbidden:** merge, concat.",
        ],
        ["# 1. Load transactions.csv"],
    ),
    (
        [
            "**Метрики событий (raw_events.csv)**",
            "event_id, user_id, event_date (DD.MM.YYYY), event_type, value.",
            "1. dtype; parse dates; drop_duplicates event_id (first).",
            "2. fillna value медианой по event_type.",
            "3. События 2023 года; groupby event_type: count_events, avg_value, total_value.",
            "4. share_of_total; `event_metrics_2023.csv` (utf-8-sig).",
        ],
        [
            "**Event metrics (raw_events.csv)**",
            "Columns: event_id, user_id, event_date (DD.MM.YYYY), event_type, value.",
            "1. Explicit dtypes; parse dates; dedupe event_id (keep first).",
            "2. fillna value with median by event_type.",
            "3. 2023 events only; groupby event_type: count_events, avg_value, total_value.",
            "4. share_of_total; save `event_metrics_2023.csv` (utf-8-sig).",
        ],
        None,
    ),
    (
        [
            "**Региональная активность (users.csv + sessions.csv)**",
            "1. Parse dates; sessions: drop duration_sec <= 0; fillna duration → 0.",
            "2. left merge validate 1:m; user_tenure_days = session_date − signup_date.",
            "3. По region: total_sessions, avg_duration, active_users (duration > 0).",
            "4. Фильтр active_users >= 30 → `regional_activity.csv`.",
        ],
        [
            "**Regional activity (users.csv + sessions.csv)**",
            "1. Parse dates; sessions: drop duration_sec <= 0; fillna duration with 0.",
            "2. left merge validate 1:m; user_tenure_days = session_date − signup_date.",
            "3. Per region: total_sessions, avg_duration, active_users (duration > 0).",
            "4. Filter active_users >= 30 → save `regional_activity.csv`.",
        ],
        None,
    ),
    (
        [
            "**Когортный дашборд (transactions.csv)**",
            "1. amount > 0; dedupe user_id + transaction_date.",
            "2. cohort и tx_month (YYYY-MM); revenue и buyers по паре.",
            "3. cohort_revenue (месяц 0) через transform; revenue_retention.",
            "4. month_diff 0…5; pivot cohort × month_diff → `cohort_dashboard.csv`.",
        ],
        [
            "**Cohort dashboard (transactions.csv)**",
            "1. amount > 0; dedupe user_id + transaction_date.",
            "2. cohort and tx_month (YYYY-MM); revenue and buyers per pair.",
            "3. cohort_revenue (month 0) via transform; revenue_retention.",
            "4. month_diff 0…5; pivot cohort × month_diff → `cohort_dashboard.csv`.",
        ],
        None,
    ),
)


BUSINESS = _pairs(
    (
        [
            "## 📊 Задача: аудит региональных продаж",
            "**Контекст:** широкая таблица по месяцам скрывает динамику регионов.",
            "1. melt → product, region, month, revenue.",
            "2. Доля месяца в годовой выручке пары product–region.",
            "3. Фильтр доли > 22%.",
            "4. pivot_table: product × region, сумма отфильтрованной выручки; пропуски → 0.",
            "5. Экспорт CSV.",
            "**Разрешено:** melt, transform, pivot_table, to_csv. **Запрещено:** merge, concat, apply, циклы.",
        ],
        [
            "## 📊 TASK: Regional Sales Audit",
            "**Context:** wide monthly columns hide regional dynamics.",
            "1. melt → product, region, month, revenue.",
            "2. Month share of annual revenue per product–region pair.",
            "3. Keep months with share > 22%.",
            "4. pivot_table: product × region, sum filtered revenue; fill 0.",
            "5. Export CSV.",
            "**Allowed:** melt, transform, pivot_table, to_csv. **Forbidden:** merge, concat, apply, loops.",
        ],
        None,
    ),
    (
        [
            "## 📊 Задача 1: Customer 360",
            "**Контекст:** CRM и биллинг раздельно; нужна единая master-таблица.",
            "crm_raw + billing_raw; cust_id как текст; drop_duplicates.",
            "left merge: total_invoices, max_invoice_amount; все клиенты, даже без покупок.",
            "signup_date: медиана по region; is_high_value если max_invoice_amount > 200.",
            "→ `customer_master.csv` (cust_id, region, signup_date, total_invoices, max_invoice_amount, is_high_value).",
            "**Разрешено:** read_csv, drop_duplicates, groupby+agg, merge(left), fillna, np.where, to_csv.",
        ],
        [
            "## 📊 TASK 1: Customer 360 Cleanup",
            "**Context:** separate CRM and billing; need one master table.",
            "Load crm_raw + billing_raw; cust_id as text; drop_duplicates.",
            "left merge: total_invoices, max_invoice_amount; keep all customers.",
            "signup_date: regional median fillna; is_high_value if max_invoice_amount > 200.",
            "→ `customer_master.csv` (cust_id, region, signup_date, total_invoices, max_invoice_amount, is_high_value).",
            "**Allowed:** read_csv, drop_duplicates, groupby+agg, merge(left), fillna, np.where, to_csv.",
        ],
        None,
    ),
    (
        [
            "# 📊 Задача 2: вовлечённость и риск оттока",
            "**Данные:** `user_events.csv`",
            "1. Parse event_date; month YYYY-MM.",
            "2. Сессии: разрыв > 30 мин → новый session_id (sort, diff, cumsum).",
            "3. session_duration, event_count на session_id.",
            "4. user_global_avg_duration; monthly_avg_duration по user-month.",
            "5. is_at_risk если monthly_avg_duration < 70% baseline.",
            "6. Пользователи с ≥3 разными месяцами активности.",
            "7. → `churn_risk_analysis.csv`.",
            "**Запрещено:** apply, циклы, merge (используйте transform).",
        ],
        [
            "# 📊 Task 2: User Engagement & Churn Risk",
            "**Data:** `user_events.csv`",
            "1. Parse event_date; month YYYY-MM.",
            "2. Sessions: gap > 30 min → new session_id (sort, diff, cumsum).",
            "3. session_duration, event_count per session_id.",
            "4. user_global_avg_duration; monthly_avg_duration per user-month.",
            "5. is_at_risk if monthly_avg_duration < 70% of personal baseline.",
            "6. Users active in at least 3 distinct months.",
            "7. Save `churn_risk_analysis.csv`.",
            "**Forbidden:** apply, loops, merge (use transform).",
        ],
        None,
    ),
    (
        [
            "# 📊 Задача 3: концентрация каналов",
            "**Данные:** `channel_sales_wide.csv` (годовая выручка).",
            "1. melt → product, channel, revenue; drop revenue 0/NaN (вывести число удалённых).",
            "2. share_of_product, share_of_channel, share_of_total (transform sum).",
            "3. hhi_product = Σ(share_of_product²) на продукт.",
            "4. risk_class: dominant (>35%), core (10–35%), long_tail (<10%).",
            "5. Сводка по продукту: total_revenue, hhi_product, top_channel (idxmax), top_channel_share.",
            "6. → `channel_pairs_long.csv`, `product_concentration_summary.csv`.",
        ],
        [
            "# 📊 Task 3: Channel Concentration & Risk",
            "**Data:** `channel_sales_wide.csv` (annual revenue).",
            "1. melt → product, channel, revenue; drop 0/NaN (print drop count).",
            "2. share_of_product, share_of_channel, share_of_total (transform sum).",
            "3. hhi_product = Σ(share_of_product²) per product.",
            "4. risk_class: dominant (>35%), core (10–35%), long_tail (<10%).",
            "5. Product summary: total_revenue, hhi_product, top_channel (idxmax), top_channel_share.",
            "6. Save `channel_pairs_long.csv`, `product_concentration_summary.csv`.",
        ],
        [
            "# После чтения: годовая выручка по каналам.",
            "# melt широкой таблицы в длинную.",
        ],
    ),
)
